//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniBandidas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id { get; set; }
        public string presentacion { get; set; }
        public string topping1 { get; set; }
        public string topping2 { get; set; }
        public int cantidad { get; set; }
        public decimal precio { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
